name: Build PDF from Markdown

on:
  push:
    branches:
      - main  # Trigger on push to main branch; adjust as needed

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checks-out your repository under $GITHUB_WORKSPACE

      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # Specify the Python version

      - name: Install pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          sudo apt-get install -y texlive-xetex  # MiKTeX alternative for Ubuntu

      - name: Create and activate virtual environment
        run: |
          python -m pip install virtualenv
          python -m virtualenv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .

      - name: Generate PDF
        run: |
          swent_prd generate --team 21 template

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Generated-PDF
          path: Team_21_prd.pdf
